name: install-netlify-package
on: [push]
jobs:
  check-netlify-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm cache clean --force
      - run: rm -rf node_modules
      - run: rm package-lock.json
      - run: npm install
      - run: npm install netlify-cli -g
      - run: npm netlify -v
